[project]
name = "ai-nakamura"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "gym>=0.26.2",
    "opencv-python>=4.12.0.88",
    "torch>=2.7.1",
]
